---
title: "School_meals_report"
author: "Chris LeBoa"
date: "6/12/2020"
output: 
  github_document:
    toc: true
---

#Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(googlesheets4)
```

## Read in Data

```{r cars}
school_meals <- 
  read_sheet(
    ss = "1fea1BSSAhbSB0HLsatDaD8wxmwsF7ezQjNvjRK-QJQI", 
    skip = 1,
    col_types = "ccccccccccccccccccccccccccccccc"
  ) %>% 
  rename(
    "district_name" = provider_addloc,
    "site_name" = provider_name
  )
school_meals
```

## Cleaning data 

```{r}
school_meals_months <- 
  school_meals %>% 
  filter(status == "Open") %>% 
  mutate(
    end_date = 
    case_when(
      str_detect(end_date, "June") == TRUE ~ "6/30",
      str_detect(end_date, "end of school year") == TRUE ~ NA_character_,
      str_detect(end_date, "06") == TRUE ~ "6/12", 
      TRUE ~ end_date
      ),
    end_month = 
      case_when(
      str_detect(end_date, "05/|5/") == TRUE ~ "End date TBC",
      str_detect(end_date, "06/|6/") == TRUE ~ "June", 
      str_detect(end_date, "07/|7/") == TRUE ~ "July",
      str_detect(end_date, "08/|8/") == TRUE ~ "August", 
      str_detect(end_date, "Until further notice") == TRUE ~ "End date TBC",
      is.na(end_date) == TRUE ~ "End date TBC", 
      TRUE ~ end_date
      )
  ) 

school_meals_months 

```

## Basic counts of schools still open

```{r}

school_meals %>% 
  filter(!is.na(status), status != "status") %>% 
  count(status)

school_meals %>% 
  distinct(site_name)

school_meals %>% 
  filter(!is.na(status)) %>% 
  distinct(district_name) #146 school districts 


```

### Schools PEBT information details 
```{r}

school_meals %>% 
  filter(!is.na(pebt_info_yn)) %>% 
  count(pebt_info_yn)

school_meals %>% 
  filter(pebt_info_yn == "1") %>% 
  distinct(pebt_notes)


school_meals %>% 
  filter(str_detect(pebt_notes, "Flyer|flyer|flier|app")) %>% 
  distinct(pebt_notes)

school_meals %>% 
  filter(pebt_info_yn == "1") %>% 
  distinct(site_name)  #43 report 

meals_pebt <- 
  school_meals %>% 
  filter(pebt_info_yn == "1") %>% 
  group_by(district_name) %>% 
  count(links_to_cfa, links_to_CDSS, contains_original_info, pebt_notes)

# meals_pebt %>% 
#   write_csv("/Users/ChrisLeBoa/Downloads/pebt_districts.csv")

meals_pebt %>% 
  mutate(
    links_to_cfa = as.numeric(links_to_cfa),
    links_to_CDSS = as.numeric(links_to_CDSS), 
    contains_original_info = as.numeric(contains_original_info)
    ) %>% 
  ungroup() %>% 
  summarise_at(c("links_to_cfa", "links_to_CDSS", "contains_original_info"), sum, na.rm = TRUE)

```



### Schools ending summer distribution 
```{r}

#Count months by school location

school_meals_months %>% 
  summarize(total_sites = n())

school_meals_months %>% 
  summarize(total_districts = n_distinct(district_name))

school_meals_months %>% 
  count(end_month) %>% 
  rename("no_schools" = n) %>% 
  mutate(pct_schools = no_schools * 100 / sum(no_schools))

school_meals_months %>%
  group_by(end_month) %>% 
  count(district_name, name = "Number of Schools") %>% 
  count(end_month) %>% 
  rename("no_districts" = n)

school_meals %>% 
  filter(county != "county") %>% 
  distinct(county)


```

## Join with CalFresh
```{r}

# cflink <- "/Users/joycetagal/Google Drive (jtagal@stanford.edu)/Bay Area Community Resources - Mega map/Data/CalFresh/last_365_by_zip_060120.csv"
# 
# cf <- read_csv(cflink)
# 
# cf

```

## Join with FRPM
```{r}

frlink <- "/Users/joycetagal/GitHub/jayktee/bay-area-resources/bay_area_resources/data/frpm1920.xlsx"

frpm <- 
  readxl::read_xlsx(frlink, sheet = 2, skip = 1) %>% 
  rename_all(.funs = ~str_to_lower(.) %>% str_replace_all(., " ", "_") %>% str_replace_all(., "[()\\n//-]", "") %>% str_replace(., "%", "pct"))

frpm

```

```{r}

frpm %>% 
  distinct(district_type)

frpm %>% 
  distinct(district_name)

```

### Clean district names

```{r}

school_meals_clean <- 
  school_meals_months %>% 
  filter(
    !district_name %in% 
      c("YMCA Silicon Valley", 
        "San Mateo County Library",
        "Voices College Bound",
        "Ace Charter Schools",
        "Alpha Public Schools",
        "Downtown College Prep",
        "Summit Public Schools",
        "Rocketship Public Schools"
      )
  )

school_meals_clean

```

Checking for intersection between datasets

```{r}

intersect(
  school_meals_clean %>% 
  distinct(district_name),
  frpm %>% 
  distinct(district_name)
)

```

```{r}
districts <- school_meals_clean %>% distinct(district_name) %>% pull()

frpm_districts <- 
  frpm %>% 
  filter(district_name %in% districts) %>% 
  select(
    academic_year, 
    county_name, 
    district_name, 
    enrollment_k12, 
    free_meal_count_k12,
    percent_pct_eligible_free_k12,
    frpm_count_k12,
    percent_pct_eligible_frpm_k12
  ) %>% 
  group_by(district_name) %>% 
  summarize(
    total_enroll = sum(enrollment_k12),
    free_meal_count_k12 = sum(free_meal_count_k12),
    frpm_count_k12 = sum(frpm_count_k12)
  ) %>% 
  mutate(
    percent_pct_eligible_free_k12 = free_meal_count_k12 / total_enroll,
    percent_pct_eligible_frpm_k12 = frpm_count_k12 / total_enroll
  )

frpm_districts %>% summarise(total_enroll = sum(total_enroll))

```


```{r}

# school_meals_clean %>%
#   left_join(
#     frpm_districts,
#     by = "district_name"
#   ) %>% 
#   group_by(district_name) %>% 
#   summarize(total_enroll = sum(total_enroll), .groups = "drop_last")

school_meals_average <- 
  school_meals_clean %>%
  group_by(district_name) %>% 
  count(end_month, name = "num_schools") %>% 
  left_join(
    frpm_districts,
    by = "district_name"
  ) %>% 
  group_by(end_month) %>%
  summarize(
    num_schools = sum(num_schools),
    total_enroll = sum(total_enroll),
    total_free_eligible = sum(free_meal_count_k12),
    total_frpm_eligible = sum(frpm_count_k12),
  .groups = "keep") %>% 
  mutate(
    percent_eligible_free_k12 = total_free_eligible / total_enroll,
    percent_eligible_frpm_k12 = total_frpm_eligible / total_enroll
  ) %>% 
  pivot_longer(
    cols = c(percent_eligible_free_k12, percent_eligible_frpm_k12),
    names_to = "type",
    values_to = "percent_eligible"
  ) 

school_meals_average

```

```{r}

## DO NOT USE YET
school_meals_average %>% 
  filter(type == "percent_eligible_frpm_k12") %>% 
  ggplot(aes(x = end_month, y = percent_eligible)) +
  geom_col() +
  ggrepel::geom_text_repel(
    aes(label = scales::percent(percent_eligible)),
    direction = "y",
    nudge_y = 0.01,
    size = 3.5
  ) +
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  coord_cartesian(expand = TRUE) +
  labs(
    title = "Average percentage of children eligible for FRPM in districts closing meal sites",
    y = "Average percentage children eligible for Free-Reduced Meals",
    x = "Months"
  )
ggsave("percentage_districts.png", height = 5, width = 7)
  

school_meals_average %>% 
  filter(type == "percent_eligible_frpm_k12") %>% 
  ggplot(aes(x = end_month, y = total_frpm_eligible)) +
  geom_col() +
  ggrepel::geom_text_repel(
    aes(label = scales::comma(total_frpm_eligible)),
    direction = "y",
    nudge_y = 3,
    size = 3.5
  ) +
  scale_y_continuous(labels = scales::label_number_si(accuracy = 1)) +
  coord_cartesian(expand = TRUE) +
  labs(
    title = "Number of children eligible for FRPM in districts closing meal sites",
    y = "Total children eligible for Free-Reduced Meals",
    x = "Months"
  )
ggsave("total_districts.png", height = 4, width = 7)

# school_meals_average %>% 
#   filter(type == "percent_eligible_frpm_k12") %>% 
#   ggplot(aes(x = end_month, y = total_enroll)) +
#   geom_col()


```

